import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import { Providers } from './providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[url('/images/background.jpg')] bg-cover h-screen`}>
        <Providers>
          <Navbar />
          <div className='container bg-white my-10 m-auto h-5/6'>
            {children}
          </div>
        </Providers>
      </body>
    </html>
  )
}
